trigger: none
variables:
  - group: SharedVariables
pool:
   name: $(poolName-TEP-PROD)
   demands:
     - agent.name -equals TEPPortal-PROD-agent
resources:
  repositories:
    - repository: PipelineTemplates
      type: git
      name: Pluto/PipelineTemplates
steps:
- task: UseNode@1
  displayName: 'Use Node.js 20.x'
  inputs:
    version: '20.x'
- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'ci'
- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: CopyFiles@2
  displayName: 'Copy files to Publish folder'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\dist'
    Contents: '**'
    TargetFolder: 'C:\DevOps\PublishedFiles\TxTEPPortal'
    CleanTargetFolder: true
- template: cd-pipeline.yml@PipelineTemplates
  parameters:
    solutionName: 'TxTEPPortal'
    websiteName: 'TxTEPPortal'