export const LOV_TAGS = [
  'SADAD_BILLERS',
  'ATTRIBUTES',
  'SADAD_GOVERNMENT_SERVICES',
  'BANKS',
  'ATTRIBUTE_TRANSFORMATON',
  'ARNBSARI_IPS_REJECTION_CODES',
  'ARNBSARI_TRANSACTION_TYPES',
  'EXTRACTIONS',
  'COUNTRIES',
  'DEMO_USER_COMPS',
  'CARD_TYPES'
] as const;
